services:
  discord-cdn:
    name: discord-cdn
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - TOKEN=${TOKEN}
      - PORT=${PORT:-8080}
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
